{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.javautils",
    "module": "java-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l2mqbji24fd47ok5f452rfheuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 4721,
          "sha512": "e5ed159e0446ce3a477f2371499a126ce3843f6590937bb6de09391238ef272b32641ac6c718986ee584ce14c6ea5306b9b0db163a0d040a2a925ffe89138f5e",
          "sha256": "40b43e54f62d8aae00105d997ab9ea76c3c3b6c11b383651c0f6e9353b077d83",
          "sha1": "9eafbb696862f2f6a2bf0c6eeb28444702b4bbf2",
          "md5": "a8ee2127c1f38972728c915b3c1531e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 4721,
          "sha512": "e5ed159e0446ce3a477f2371499a126ce3843f6590937bb6de09391238ef272b32641ac6c718986ee584ce14c6ea5306b9b0db163a0d040a2a925ffe89138f5e",
          "sha256": "40b43e54f62d8aae00105d997ab9ea76c3c3b6c11b383651c0f6e9353b077d83",
          "sha1": "9eafbb696862f2f6a2bf0c6eeb28444702b4bbf2",
          "md5": "a8ee2127c1f38972728c915b3c1531e3"
        }
      ]
    }
  ]
}
