{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.javautils",
    "module": "java-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lldlhmddq5grposvjothacvxxa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 3448,
          "sha512": "14cb0315316a6d8c10c0353c07e3711959515f2e20a171cb16f28c60ba8eb41b1b84a98b454584881e57546d2b604d2db7073c8b92c2301e4427c2acf4421757",
          "sha256": "4ede4808561cd3a7a30fb6ab1dfe82ce4510dcc06890ab5b745e1c1b7062d319",
          "sha1": "a8200a829aad2461d03b33b8821084350b995870",
          "md5": "d88776f09cf421201b173d8af52b3306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 3448,
          "sha512": "14cb0315316a6d8c10c0353c07e3711959515f2e20a171cb16f28c60ba8eb41b1b84a98b454584881e57546d2b604d2db7073c8b92c2301e4427c2acf4421757",
          "sha256": "4ede4808561cd3a7a30fb6ab1dfe82ce4510dcc06890ab5b745e1c1b7062d319",
          "sha1": "a8200a829aad2461d03b33b8821084350b995870",
          "md5": "d88776f09cf421201b173d8af52b3306"
        }
      ]
    }
  ]
}
