{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.javautils",
    "module": "java-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6vyx5oyi3fdxpbr4xvoacqupra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 4487,
          "sha512": "6ba82e1476af9bcd67e136832972220ba648b63a8bbcf25eb6f91d4b3cb6561fb34cf06b0e5fe836bcef07f67dfdc5e7b77425bce819b260bfb1d9d01677d226",
          "sha256": "60a1ed1fc5149e9e06c0a7a60ca4328995b7769bf7917c51bbe97d9e654342bd",
          "sha1": "bbff80f3051b8ef3013a4fdcf14ea5ec9e38ae4c",
          "md5": "35a853862d32f08ecff1e5fccd87f58a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-utils-0.0.1.jar",
          "url": "java-utils-0.0.1.jar",
          "size": 4487,
          "sha512": "6ba82e1476af9bcd67e136832972220ba648b63a8bbcf25eb6f91d4b3cb6561fb34cf06b0e5fe836bcef07f67dfdc5e7b77425bce819b260bfb1d9d01677d226",
          "sha256": "60a1ed1fc5149e9e06c0a7a60ca4328995b7769bf7917c51bbe97d9e654342bd",
          "sha1": "bbff80f3051b8ef3013a4fdcf14ea5ec9e38ae4c",
          "md5": "35a853862d32f08ecff1e5fccd87f58a"
        }
      ]
    }
  ]
}
